name: asman_rider
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  rider_ui:
    path: ./packages/rider_ui
  data_provider:
    path: ./packages/data_provider
  storage:
    path: ./packages/storage/storage
  secure_storage:
    path: ./packages/storage/secure_storage
  persistent_storage:
    path: ./packages/storage/persistent_storage
  form_inputs:
    path: ./packages/form_inputs
  user_repository:
    path: ./packages/user_repository
  ride_repository:
    path: ./packages/ride_repository
  order_repository:
    path: ./packages/order_repository
  protos:
    path: ./packages/protos

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flow_builder: ^0.0.9
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  url_launcher: ^6.1.12
  android_intent_plus: ^4.0.1
  flutter_screenutil: ^5.8.4
  shared_preferences: ^2.2.0
  bloc_concurrency: ^0.2.2
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  sliver_tools: ^0.2.12
  simple_barcode_scanner: ^0.0.8
  grpc: ^3.2.3
  location: ^5.0.1
  slide_action: ^0.0.2
  slide_to_act: ^2.0.1
  cached_network_image: ^3.2.3
  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.0
  float_column: ^2.1.1
  intl: ^0.18.1
  flutter_hooks: ^0.20.1
  rxdart: ^0.27.7
  firebase_analytics: ^10.4.5
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_messaging: ^14.6.7
  flutter_local_notifications: ^15.1.1
  device_info_plus: ^9.0.3
  dio: ^5.3.2
  envied: ^0.3.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3

dependency_overrides:
  intl: ^0.18.1

flutter:
  generate: true
  uses-material-design: true
