name: ride_repository
description: Ride Repository
publish_to: none

environment:
  sdk: ^3.0.6

dependencies:
  data_provider:
    path: ../data_provider
  equatable: ^2.0.5

dev_dependencies:
  test: ^1.21.0
  very_good_analysis: ^4.0.0
